### PR TITLE
adding before_install step

### PR DESCRIPTION
**Pull request by vsilverman**

### CODE REVIEW

**Comment by johngmyers** [comment]
There doesn't seem to be anything here of value. The extra step with library is unnecessary and I don't see the point of the before_install step.

**Comment by johngmyers** [comment]
Are you perhaps trying to fish out credentials from Travis?

**Comment by vsilverman** [comment]
Proposing to add README and providing it's initial content to help building the platform from the sources.

**Comment by johngmyers** [comment]
Nothing here of value. Declining.

**Pull request closed without merging**
