### PR TITLE
Start migrating the bindConfig() DSL to ConfigBinder

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by johngmyers** [comment]
I wonder if we want to change the EDSL to be more like:

```java
configBinder(binder).bind(FooConfig.class)
   .annotatedWith(Red.class)
   .prefixedWith("prefix");
```

**Comment by gwittel** [comment]
Using `bind` as the entry point would be more consistent with the other binders.

Was it intentional to not mark the `ConfigurationModule.bind()` method as deprecated?

**Comment by johngmyers** [comment]
I want to delay deprecating `ConfigurationModule.bindConfig()`  until `ConfigBinder` has existed for a while. It's currently used everywhere.

**Comment by johngmyers** [comment]
Will resubmit with changed EDSL.

**Pull request closed without merging**
