### PR TITLE
TestingResponse improvements

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by gwittel** [comment]
LGTM

**Comment by johngmyers** [comment]
Rebased. Added a commit to remove the "charset=utf-8" parameter from the content-type of JSON responses. This is to match the usual practice with the JAX-RS resources being mocked.

**Comment by gwittel** [comment]
Rebase LGTM

**Comment by johngmyers** [comment]
Rebased, squashed fixup commit, and merged

**Pull request closed without merging**
