### PR TITLE
Support AutoValue event classes

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by gwittel** [comment]
Looks good overall.  Here we no longer cover non-AutoValue event classes explicitly.  Do we feel the need for exlicit coverage, or is the generated Autovalue code equivalent enough?

**Comment by johngmyers** [comment]
There are several test cases that use non-AutoValue event classes. They are primarily cases that AutoValue doesn't cover, like event classes that subclass other event classes.

**Comment by gwittel** [comment]
Ah ok, I was only looking at the diff vs the full codebase.

**Comment by johngmyers** [comment]
Rebased, added CHANGES, and merged

**Pull request closed without merging**
